dotnet_csproj:
  patch: true
  file: '**/*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

image:
  - Visual Studio 2017

platform:
  - Any CPU

build_script:
  - pwsh: dotnet build --configuration Release
  - pwsh: dotnet test test/AD.Xml.Tests --configuration Release